In [2]:
import numpy as np
import pandas as pd
import math

In [11]:
df_2021 = pd.read_csv('KCPD_Crime_Data_2021.csv')
df_2022 = pd.read_csv('KCPD_Crime_Data_2022.csv')
df_2023 = pd.read_csv('KCPD_Crime_Data_2023.csv')

C:\Users\rasua\AppData\Local\Temp\ipykernel_27872\3815613737.py:1: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2021 = pd.read_csv('KCPD_Crime_Data_2021.csv')
C:\Users\rasua\AppData\Local\Temp\ipykernel_27872\3815613737.py:2: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2022 = pd.read_csv('KCPD_Crime_Data_2022.csv')

In [12]:
df_2021.head()

,Report_No,Reported_Date,Reported_Time,From_Date,From_Time,To_Date,To_Time,Offense,IBRS,Description,...,Rep_Dist,Area,DVFlag,Involvement,Race,Sex,Age,Firearm Used Flag,Location,Age_Range
0,KC21055624,08/21/2021,19:45,08/21/2021,19:45,NaN,NaN,Murder,09A,Murder,...,PJ2878,EPD,False,VIC,B,M,NaN,True,NaN,NaN
1,KC21012401,02/24/2021,11:35,02/24/2021,11:35,NaN,NaN,Stealing from Building/Residence,23D,Theft From Building,...,PJ6174,MPD,False,SUS,B,M,NaN,False,NaN,NaN
2,KC21017210,03/17/2021,15:46,03/17/2021,15:35,NaN,NaN,Assault (Aggravated),13A,Aggravated Assault,...,NaN,SCP,False,ARR CHA,B,M,33.0,True,NaN,25-34
3,KC21005420,01/25/2021,11:18,01/25/2021,11:00,NaN,NaN,Recovered Stolen Auto,NaN,NaN,...,NaN,CPD,False,SUS,W,F,20.0,False,NaN,18-24
4,KC21010791,02/17/2021,11:41,02/11/2021,20:30,02/11/2021,20:45,Stolen Auto,240,Motor Vehicle Theft,...,PJ4215,MPD,False,SUS,W,M,NaN,False,NaN,NaN

In [23]:
df_2021['Offense'].unique()

array(['Murder', 'Stealing from Building/Residence',
       'Assault (Aggravated)', 'Recovered Stolen Auto', 'Stolen Auto',
       'Domestic Violence Assault (Non-Aggravated)',
       'Robbery (Armed Street)', 'Vehicular – Non-Injury',
       'Vehicular – Injury', 'Dead Body', 'Forgery', 'Identity Theft',
       'Miscellaneous Investigation', 'City/Municipal Warrant Arrest',
       'Stealing – Shoplift', 'Trespass of Real Property',
       'Soliciting Prostitution', 'Stealing from Auto (Theft from Auto)',
       'Embezzlement', 'Assault (Non-Aggravated)', 'Loss',
       'Patronizing Prostitution', 'Disorderly Conduct',
       'Sodomy - Juvenile', 'Stealing – Other',
       'Missing/Runaway Juvenile', 'Terroristic Threats',
       'Property Damage', 'Possession of Stolen Property',
       'Robbery (Residential)', 'Robbery (Strong Armed Street)',
       'Obstructing and Resisting an Officer',
       'Violation of Full Order of Protection', 'Recovered Property',
       'Tow-In Report/Authorization Not to Tow',
       'Harassment / Intimidation - Sex Crimes', 'Suicide – Attempted',
       'Endangering the Welfare of a Child',
       'Legacy Incident Report/Arrest', 'Rape', 'Unfounded',
       'Mental Health/Crisis Intervention Team (CIT) Report', 'Arson',
       'Eluding / Resisting a Lawful Stop',
       'Outside State Warrant Arrest', 'Burglary (Residential)',
       'Sexual Misconduct', 'Abuse of a Child', 'Rape - Juvenile',
       'Possession/Sale/Distribution of a Controlled Substance',
       'Burglary (Non-Residential)',
       'Domestic Violence Robbery (Strong-Armed)', 'Casualty',
       'Harassment / Intimidation - Domestic Violence',
       'State Warrant Arrest', 'Molestation', 'Suicide',
       'Alcohol Influence Report',
       'Violation of Ex-Parte Order of Protection', 'Tampering',
       'Domestic Violence Property Damage',
       'Domestic Violence Assault (Aggravated)', 'City Weapons Offense',
       'Receiving Stolen Property', 'Robbery (Business)',
       'Parental Abduction', 'Miscellaneous City Ordinance Violation',
       'Vehicular – Non-Injury Hit and Run', 'Interdiction',
       'Fraud / Stealing Through Deceit (Scam/Confidence Game)',
       'Possession/Distribution of Child Pornography', 'Sodomy',
       'Domestic Violence Robbery (Armed)', 'Abandonment of a Child',
       'Liquor Law Violation',
       'Stealing from Auto (Auto Part or Accessory)',
       'Child Custody Violation', 'Attempt to Locate Motor Vehicle',
       'Felon/Prohibited Person in Possession of a Firearm/Ammunition/Body Armor',
       'Stalking', 'Kidnapping', 'Fraudulent Use of a Credit Device',
       'Assault (Non-Aggravated) on Department Member/Outside Law Enforcement Officer',
       'Driving While Suspended/Revoked (State Offense)',
       'Vehicular – Injury Hit and Run',
       'Assault (Aggravated) on Department Member/Outside Law Enforcement Officer',
       'Sexual Abuse - Juvenile', 'False Report',
       'Failure to Return Leased or Rented Property',
       'Possession of Illegal Firearm',
       'Financial Exploitation of the Elderly',
       'Fraudulently Obtaining a Controlled Substance', 'Missing Person',
       'Domestic Violence Burglary (Residential)',
       'Tavern/Nightclub Response Report', 'Rape – Statutory',
       'Sexual Misconduct - Juvenile', 'Elder Abuse',
       'Invasion of Privacy', 'Possession of Drug Paraphernalia',
       'Sexual Abuse', 'Enticement of a Minor',
       'Stealing from Coin Operated Device', 'Passing Bad Checks',
       'Impersonation of Another Person',
       'Police Vehicle Damage (Form 154 P.D.)', 'Stealing – Purse Snatch',
       'Service of an Ex-Parte Order of Protection',
       'Hacking/Computer Invasion', 'Unlawful Endangerment of Another',
       'Vehicular – Fatality',
       'Possession/Sale/Distribution of an Imitation Controlled Substance',
       'False Bomb Report', 'Robbery (Financial Institution)',
       'Burning or Exploding', 'Stealing – Pickpocket',
       'Animal Abuse/Cruelty', 'Human Trafficking/Commercial Sex Acts',
       'Recovered Missing/Runaway Juvenile',
       'Service of a Full Order of Protection', 'Juvenile Apprehension',
       'Trafficking in Identifications', 'Carrying a Concealed Weapon',
       'Animal Bite', 'Promoting Prostitution', 'Incest',
       'Possession of Gambling Device or Records',
       'Adult Entertainment Violation', 'Discharge of Firearm (LEO Only)',
       'Unregistered Sex Offender', 'Outside Correspondence'],
      dtype=object)

In [25]:
data2021 = df_2021['Offense'].value_counts().reset_index()
data2021.columns = ['Type', '2021']
data2022 = df_2022['Offense'].value_counts().reset_index()
data2022.columns = ['Type', '2022']
data2023 = df_2023['Offense'].value_counts().reset_index()
data2023.columns = ['Type', '2023']

In [ ]:
merged_df = pd.merge(data2021, data2022, on='Type', how='outer')
merged_df = pd.merge(merged_df, data2023, on='Type', how='outer')

In [ ]:
merged_df.to_csv('Kansas_212223.csv', index = False)

In [14]:
df_2022.head()

,Report_No,Reported_Date,Reported_Time,From_Date,From_Time,To_Date,To_Time,Offense,IBRS,Description,...,Rep_Dist,Area,DVFlag,Involvement,Race,Sex,Age,Fire Arm Used Flag,Location,Age_Range
0,KC22000883,12/27/2021,11:18,12/27/2021,12:07,12/27/2021,12:09,Stealing - Shoplift,23C,Shoplifting,...,PP0281,NPD,False,VIC,NaN,NaN,NaN,False,NaN,NaN
1,KC22002461,12/31/2021,15:27,12/31/2021,18:00,12/31/2021,NaN,Stealing - Other,23H,All Other Larceny,...,NaN,SCP,False,VIC,NaN,NaN,NaN,False,NaN,NaN
2,KC22005417,01/22/2022,13:24,01/22/2022,20:00,01/22/2022,13:00,Stolen Auto,240,Motor Vehicle Theft,...,PJ2256,CPD,False,VIC,NaN,NaN,NaN,False,NaN,NaN
3,KC22017024,03/15/2022,13:27,03/15/2022,11:00,03/15/2022,NaN,Stolen Auto,240,Motor Vehicle Theft,...,NaN,CPD,False,SUS,B,M,NaN,False,NaN,NaN
4,KC22018275,03/19/2022,15:48,03/19/2022,20:00,03/19/2022,04:00,Stolen Auto,240,Motor Vehicle Theft,...,NaN,SPD,False,VIC,NaN,NaN,NaN,False,NaN,NaN

In [15]:
df_2023.head()

,Report_No,Reported_Date,Reported_Time,From_Date,From_Time,To_Date,To_Time,Offense,IBRS,Description,...,Rep_Dist,Area,DVFlag,Involvement,Race,Sex,Age,Fire Arm Used Flag,Location,Age_Range
0,KC23000049,01/01/2023,02:55,01/01/2023,02:55,NaN,NaN,Casualty,NaN,NaN,...,NaN,SCP,False,VIC,B,M,37.0,False,POINT (-94.55642 39.18363),35-44
1,KC23000684,01/03/2023,22:31,01/03/2023,22:00,NaN,NaN,Sexual Misconduct,90Z,All Other Offenses,...,PJ3601,EPD,False,VIC,NaN,NaN,NaN,False,POINT (-94.44118955199997 39.04652191400004),NaN
2,KC23000749,01/04/2023,09:21,12/22/2022,21:00,12/23/2022,10:00,Stolen Auto,240,Motor Vehicle Theft,...,PJ6036,MPD,False,VIC,B,F,89.0,False,NaN,75+
3,KC23000834,01/04/2023,16:09,01/04/2023,16:09,NaN,NaN,Stealing - Shoplift,23C,Shoplifting,...,NaN,CPD,False,VIC,NaN,NaN,NaN,False,POINT (-94.5916 39.04219),NaN
4,KC23000855,01/04/2023,17:19,01/04/2023,17:19,01/04/2023,22:30,Abuse of a Child,13B,Simple Assault,...,PC0361,NPD,False,SUS,W,M,60.0,False,POINT (-94.57961000199998 39.24576800300008),55-64

In [3]:
df_final = pd.read_csv('kansas_final.csv')
df_final.head()

         Type     2021     2022    2023
0     Murders    451.0    481.0   369.0
1       Rapes    884.0    772.0   414.0
2   Robberies   2775.0   2635.0  1201.0
3    Assaults  15216.0  15979.0  6657.0
4  Burglaries   6657.0   7093.0  3550.0

In [4]:
df_final['2021'] = df_final['2021']//5
df_final['2022'] = df_final['2022']//5
df_final['2023'] = df_final['2023']//5

In [ ]:
df_final[['2021', '2022', '2023']] = df_final[['2021', '2022', '2023']].applymap(math.floor)

In [5]:
df_final.to_csv('Kansas_final_100000.csv', index = False)